# Generated by Django 2.1.4 on 2020-01-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowData',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('score', models.FloatField(max_length=6, null=True, verbose_name='综合评分')),
                ('highest', models.FloatField(max_length=6, null=True, verbose_name='历史最高')),
                ('lowest', models.FloatField(max_length=6, null=True, verbose_name='历史最低')),
                ('average', models.FloatField(max_length=6, null=True, verbose_name='历史均价')),
                ('desire_buy', models.FloatField(max_length=6, null=True, verbose_name='买入欲望植')),
                ('desire_sell', models.FloatField(max_length=6, null=True, verbose_name='卖出欲望植')),
                ('linear_regression', models.FloatField(max_length=6, null=True, verbose_name='线性回归预测')),
                ('ridge_regression', models.FloatField(max_length=6, null=True, verbose_name='岭回归预测')),
                ('polynomial_regression', models.FloatField(max_length=6, null=True, verbose_name='多项式回归预测')),
                ('ai_prediction', models.FloatField(max_length=6, null=True, verbose_name='AI预测')),
                ('comment_tags', models.CharField(max_length=256, null=True, verbose_name='评论标签')),
                ('comment', models.TextField(null=True, verbose_name='评论')),
            ],
            options={
                'db_table': 'showdata',
            },
        ),
    ]
