# Generated by Django 2.1.4 on 2020-01-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showdata',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='showdata',
            name='comment_tags',
        ),
        migrations.RemoveField(
            model_name='showdata',
            name='desire_sell',
        ),
        migrations.AddField(
            model_name='showdata',
            name='title',
            field=models.CharField(max_length=6, null=True, verbose_name='股票名称'),
        ),
    ]
