# Generated by Django 2.1.4 on 2020-01-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20200127_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='showdata',
            name='day_count',
            field=models.FloatField(max_length=6, null=True, verbose_name='最频繁连涨出现次数'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='days',
            field=models.FloatField(max_length=24, null=True, verbose_name='最频繁连涨天数列表'),
        ),
    ]
