# Generated by Django 2.1.4 on 2020-01-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20200128_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showdata',
            name='ai_prediction',
            field=models.CharField(max_length=6, null=True, verbose_name='AI预测'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='average',
            field=models.CharField(max_length=6, null=True, verbose_name='历史均价'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='day_count',
            field=models.CharField(max_length=6, null=True, verbose_name='最频繁连涨出现次数'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='days',
            field=models.CharField(max_length=24, null=True, verbose_name='最频繁连涨天数列表'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='desire_buy',
            field=models.CharField(max_length=6, null=True, verbose_name='买入欲望植'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='highest',
            field=models.CharField(max_length=6, null=True, verbose_name='历史最高'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='linear_regression',
            field=models.CharField(max_length=6, null=True, verbose_name='线性回归预测'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='lowest',
            field=models.CharField(max_length=6, null=True, verbose_name='历史最低'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='polynomial_regression',
            field=models.CharField(max_length=6, null=True, verbose_name='多项式回归预测'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='ridge_regression',
            field=models.CharField(max_length=6, null=True, verbose_name='岭回归预测'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='score',
            field=models.CharField(max_length=6, null=True, verbose_name='综合评分'),
        ),
    ]
