# Generated by Django 2.1.4 on 2020-02-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200206_1344'),
        ('show', '0006_auto_20200201_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allnum', models.IntegerField(default=0, max_length=9, verbose_name='原始数据总条数')),
                ('stnum', models.IntegerField(default=0, max_length=9, verbose_name='股票总数')),
                ('mknum', models.IntegerField(default=0, max_length=9, verbose_name='生成数据总个数')),
                ('usernum', models.IntegerField(default=0, max_length=9, verbose_name='用户总数')),
                ('ttt', models.IntegerField(default=0, max_length=9, verbose_name='累计追踪次数')),
                ('date', models.DateField(verbose_name='统计日期')),
            ],
            options={
                'db_table': 'statsdata',
            },
        ),
        migrations.AddField(
            model_name='showdata',
            name='beat',
            field=models.FloatField(max_length=8, null=True, verbose_name='击败率'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='date',
            field=models.DateField(null=True, verbose_name='最后更新日期'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='fans',
            field=models.ManyToManyField(to='user.UserProfiles'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='fp',
            field=models.FloatField(max_length=8, null=True, verbose_name='下跌概率'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='hot',
            field=models.FloatField(max_length=8, null=True, verbose_name='下跌概率'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='lkc',
            field=models.IntegerField(max_length=8, null=True, verbose_name='昨日访问次数'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='nlp',
            field=models.CharField(max_length=50, null=True, verbose_name='情感分析NLP关键字'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='proage',
            field=models.CharField(max_length=60, null=True, verbose_name='年龄比例'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='proexp',
            field=models.CharField(max_length=100, null=True, verbose_name='经验比例'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='proinc',
            field=models.CharField(max_length=120, null=True, verbose_name='收入比例'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='prolev',
            field=models.CharField(max_length=20, null=True, verbose_name='杠杆比例'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='proocc',
            field=models.CharField(max_length=100, null=True, verbose_name='杠杆比例'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='propre',
            field=models.CharField(max_length=20, null=True, verbose_name='杠杆比例'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='prosex',
            field=models.CharField(max_length=10, null=True, verbose_name='男女比例'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='rp',
            field=models.FloatField(max_length=8, null=True, verbose_name='上涨概率'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='tt',
            field=models.IntegerField(max_length=8, null=True, verbose_name='累计追踪天数'),
        ),
    ]
