# Generated by Django 2.1.4 on 2020-02-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_auto_20200209_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showdata',
            name='nlp',
            field=models.CharField(max_length=200, null=True, verbose_name='情感分析NLP关键字'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='prosex',
            field=models.CharField(max_length=20, null=True, verbose_name='男女比例'),
        ),
    ]
