# Generated by Django 2.1.4 on 2020-02-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0010_auto_20200209_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='showdata',
            name='bond',
            field=models.CharField(max_length=4, null=True, verbose_name='证券交易所'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='close',
            field=models.FloatField(max_length=8, null=True, verbose_name='收盘价'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='gain',
            field=models.CharField(max_length=24, null=True, verbose_name='涨幅'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='high',
            field=models.FloatField(max_length=8, null=True, verbose_name='最高价'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='low',
            field=models.FloatField(max_length=8, null=True, verbose_name='最低价'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='open',
            field=models.FloatField(max_length=8, null=True, verbose_name='开盘价'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='rise',
            field=models.FloatField(max_length=6, null=True, verbose_name='上涨金额'),
        ),
        migrations.AddField(
            model_name='showdata',
            name='turnover',
            field=models.IntegerField(max_length=20, null=True, verbose_name='成交金额'),
        ),
    ]
