# Generated by Django 2.1.4 on 2020-02-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0011_auto_20200211_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='showdata',
            name='volume',
            field=models.IntegerField(max_length=20, null=True, verbose_name='成交量'),
        ),
    ]
