# Generated by Django 2.1.4 on 2020-02-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0013_auto_20200212_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='showdata',
            name='acc',
            field=models.FloatField(default=0, max_length=8, verbose_name='个股准确率'),
        ),
        migrations.AddField(
            model_name='stats',
            name='allacc',
            field=models.FloatField(default=0, max_length=8, verbose_name='准确率'),
        ),
    ]
