# Generated by Django 2.1.4 on 2020-02-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0014_auto_20200212_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showdata',
            name='hit',
            field=models.IntegerField(default=0, verbose_name='累计命中次数'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='lkc',
            field=models.IntegerField(default=0, verbose_name='搜索热度'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='pre_num',
            field=models.IntegerField(default=0, verbose_name='预测次数'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='tt',
            field=models.IntegerField(default=0, verbose_name='累计追踪天数'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='turnover',
            field=models.IntegerField(null=True, verbose_name='成交金额'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='view_down',
            field=models.IntegerField(default=1, verbose_name='看跌人数'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='view_up',
            field=models.IntegerField(default=1, verbose_name='看涨人数'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='volume',
            field=models.IntegerField(null=True, verbose_name='成交量'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='allnum',
            field=models.IntegerField(default=0, verbose_name='原始数据总条数'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='mknum',
            field=models.IntegerField(default=0, verbose_name='生成数据总个数'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='stnum',
            field=models.IntegerField(default=0, verbose_name='股票总数'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='ttt',
            field=models.IntegerField(default=0, verbose_name='累计追踪次数'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='usernum',
            field=models.IntegerField(default=0, verbose_name='用户总数'),
        ),
    ]
