# Generated by Django 2.1.4 on 2020-01-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('email', models.EmailField(max_length=60, verbose_name='邮箱')),
                ('gender', models.CharField(max_length=4, verbose_name='性别')),
                ('age', models.IntegerField(max_length=3, verbose_name='年龄')),
                ('avatar', models.ImageField(max_length=1000, upload_to='statoc/avatar/%Y/%m/%d/', verbose_name='头像')),
                ('salary', models.CharField(max_length=12, verbose_name='工资')),
                ('Occupation', models.CharField(max_length=4, verbose_name='职业')),
                ('partiality', models.CharField(max_length=2, verbose_name='偏好')),
                ('experience', models.CharField(max_length=3, verbose_name='股龄')),
                ('lever', models.CharField(max_length=1, verbose_name='杠杆')),
            ],
            options={
                'db_table': 'userprofiles',
            },
        ),
    ]
