# Generated by Django 2.1.4 on 2020-01-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200109_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='Occupation',
            field=models.CharField(max_length=16, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='age',
            field=models.CharField(max_length=4, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='experience',
            field=models.CharField(max_length=4, null=True, verbose_name='股龄'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='salary',
            field=models.CharField(max_length=6, null=True, verbose_name='工资'),
        ),
    ]
