# Generated by Django 2.1.4 on 2020-01-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200110_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='check_code',
            field=models.IntegerField(max_length=6, null=True, verbose_name='验证码'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='code_valid_time',
            field=models.IntegerField(max_length=10, null=True, verbose_name='验证码失效时间戳'),
        ),
    ]
