# Generated by Django 2.1.4 on 2020-02-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200111_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='Occupation',
            field=models.CharField(default='未填写', max_length=16, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='experience',
            field=models.CharField(default='未填写', max_length=4, null=True, verbose_name='股龄'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='gender',
            field=models.CharField(default='未填写', max_length=4, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='lever',
            field=models.CharField(default='未填写', max_length=1, null=True, verbose_name='杠杆'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='partiality',
            field=models.CharField(default='未填写', max_length=2, null=True, verbose_name='偏好'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='salary',
            field=models.CharField(default='未填写', max_length=6, null=True, verbose_name='工资'),
        ),
    ]
