# Generated by Django 2.1.4 on 2020-02-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200206_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='experience',
            field=models.CharField(default='未填写', max_length=5, null=True, verbose_name='股龄'),
        ),
    ]
