# Generated by Django 2.1.4 on 2020-02-13 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200212_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfiles', verbose_name='用户请求指纹'),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='finger',
            field=models.CharField(max_length=30, null=True, verbose_name='用户请求指纹'),
        ),
    ]
