# Generated by Django 2.1.4 on 2020-02-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200213_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fingerprint',
            old_name='username',
            new_name='user',
        ),
    ]
