# Generated by Django 2.1.4 on 2020-02-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200213_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户请求指纹id'),
        ),
    ]
