# Generated by Django 2.1.4 on 2020-01-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='序号')),
                ('code', models.CharField(db_index=True, max_length=18, verbose_name='股票代码')),
                ('title', models.CharField(max_length=16, verbose_name='股票名称')),
                ('bond', models.CharField(max_length=8, verbose_name='证券交易所')),
                ('date', models.DateField()),
                ('open', models.FloatField(max_length=6, verbose_name='开盘价')),
                ('close', models.FloatField(max_length=6, verbose_name='收盘价')),
                ('high', models.FloatField(max_length=6, verbose_name='最高价')),
                ('low', models.FloatField(max_length=6, verbose_name='最低价')),
                ('volume', models.IntegerField(max_length=256, verbose_name='成交量')),
                ('turnover', models.IntegerField(max_length=256, verbose_name='成交金额')),
                ('rise', models.FloatField(max_length=6, verbose_name='上涨金额')),
                ('gain', models.CharField(max_length=24, verbose_name='涨幅')),
            ],
            options={
                'db_table': 'stockdata',
            },
        ),
    ]
