# Generated by Django 2.1.4 on 2020-01-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='volume',
            field=models.IntegerField(max_length=100, verbose_name='成交量'),
        ),
    ]
