# Generated by Django 2.1.4 on 2020-02-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20200127_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='volume',
            field=models.IntegerField(max_length=50, verbose_name='成交量'),
        ),
    ]
