# Generated by Django 2.1.4 on 2020-02-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20200212_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='turnover',
            field=models.IntegerField(verbose_name='成交金额'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='volume',
            field=models.IntegerField(verbose_name='成交量'),
        ),
    ]
